general:
  driversToTest: firefoxe
  test:
    waitTimeout: 1
  driver:
    name:
      firefox: firefox
      chrome: chrome
    system:
      property:
        name:
          firefox: webdriver.gecko.driver
          chrome: webdriver.chrome.driver
        value:
          firefox: /home/tomas/Downloads/geckodriver
          chrome: /home/tomas/Downloads/chromedriver
login:
  test:
    name: login
    url: https://site.com/login
    waitTimeout: 10
    form:
      element:
        id:
        name: username
    username:
      valid: user.name@site.com
      invalid:
      element:
        class:
        id:
        name: username
    password:
      valid: $$$$$
      invalid:
      element:
        class:
        id:
        name: password
    valid:
      expectedPresenceElement: userItem
    invalid:
      expectedPresenceElement: formErrorLabel
      expectedPresenceElementText: Oops, unknown username or password.
